//triggers
export const FETCH_USER_CV = 'FETCH_USER_CV';
export const ADD_CV_FIELD = 'ADD_CV_FIELD';
export const REMOVE_CV_FIELD = 'REMOVE_CV_FIELD';
//success
export const FETCH_USER_CV_SUCCESS = 'FETCH_USER_CV_SUCCESS';
export const ADD_CV_FIELD_SUCCESS = 'ADD_CV_FIELD_SUCCESS';
export const REMOVE_CV_FIELD_SUCCESS = 'REMOVE_CV_FIELD_SUCCESS';

//error
export const REJECT_USER_CV = 'REJECT_USER_CV';
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS';
