export const RESPONSE_USER_FIELDS_DENIED = 'RESPONSE_USER_FIELDS_DENIED';
export const RESPONSE_USER_FIELDS_SUCCESS = 'RESPONSE_USER_FIELDS_SUCCESS';
export const ADD_FIELDS = 'ADD_FIELDS';
export const REMOVE_NEW_FIELD = 'REMOVE_NEW_FIELD';
export const ADD_NEW_FIELD = 'ADD_NEW_FIELD';
export const SET_USER_CARD = 'GET_USER_DATA';
