export const FETCH_ALL_COLLECTIONS = 'FETCH_ALL_COLLECTIONS';
export const ADD_NEW_COLLECTION = 'ADD_NEW_COLLECTION';
export const REMOVE_COLLECTION = 'REMOVE_COLLECTION';
export const CLEAR_COLLECTIONS_MESSAGE = 'CLEAR_COLLECTIONS_MESSAGE';

export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_ERROR = 'FETCH_COLLECTIONS_ERROR';
