//REGISTRATION
export const SET_REGISTRATION_FIELDS = 'SET_REGISTRATION_FIELDS';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const RESET_REGISTRATION = 'RESET_REGISTRATION';
